### PR TITLE
Extract annotations based on their color

### PR DESCRIPTION
**Pull request by RAG2ko**
To address issue jlegewie/zotfile#146

1) convert extracted colors from dRGB (pdf) to HSL
2) cluster colors into groups: dark green, light green, etc. -> green
3) separate annotations by color if _PDFJS.getPDFAnnotations_ is called with _useColor_ set to _true_ (_false_ will return the original annotations object without color separation)

I also added some test pdfs that contain annotations with different colors.

Please let me know what you think of my approach :)

### CODE REVIEW

**Comment by jlegewie** [comment]
Great progress! I hope you also had some fun getting into the code. I will take a closer look over the next days but here is a first question. What was the reason for using the color classification approach and the different arrays for the color classes? Can you just add one variable to the annotation array `obj.annotations` in `getPDFAnnotations.js` that includes the RGB code of the color? I change as little as possible in `getPDFAnnotations.js` and just add this variable using one function that translates the pdf colors to RGB.

**Comment by RAG2ko** [comment]
Thanks for your feedback! I definitely had fun getting into the code :)
I think the color classification is actually essential to the whole process of extraction annotations by color. Let me explain why. Let's say I use adobe pdf on my laptop but a different software on my tablet. Now, if I make a yellow annotation in each reader a strictly RGB-based extraction would split the annotations although both are yellow. This is because adobe, foxit, etc. all have different types of colors, e.g. adobe's yellow is not the same as foxit's one. So for someone who is using different readers the color based extraction should rely on color classes. Unfortunately, is not that easy to classify colors by RGB that's why I converted the color values to HSL. This makes the classification fairly easy. Overall, the whole process of conversion and classification is very fast, I was not able to see a difference in speed. Just give it a try with my test pdfs!

**Comment by jlegewie** [comment]
Okay, I get the point. I am still not sure whether I would put that categorization in `getPDFAnnotations.js` or at the place where the annotations are processed in `zotfile.js`. In any case, you shouldn't return separate annotation arrays but instead just add two variables to `obj.annotations`. First, `color` for the HSL color code (I guess an array with three values). Second, `colorCategory` for the color classification. This variable should be a string such as `'red'`, `'green'` etc. If it's no problem, I would prefer `color` in rgb (you can still categorize based on the hsl version).

**Comment by RAG2ko** [comment]
Done.
1. I reverted the annotations output back to its original state (annotations are no longer in different arrays based on their color)
2. I changed/adapted the annotation variables:
   - color: array with RGB values
   - colorHSL: array with HSL values, will be deleted if colorCategory exists and script is not running in debug mode
   - colorCategory: string, e.g. black
3. I also did some fine-tuning on the color classification.

Have a look and let me know what you think! THX.

**Comment by jlegewie** [comment]
Great progress, thanks! I still would like to reorganize the code a little but I think I can do that with the code you provided. I will take a closer look soon but I might take a couple of days.

**Comment by jlegewie** [comment]
Once I have done that, I will post again about the integration into zotfile.

**Comment by jlegewie** [comment]
Hey, I just incorporated some of your changes in zotfile (install the github version to test). Here is the commit https://github.com/jlegewie/zotfile/commit/61fd85cd1b14b1d993766f85a541490cba419182
Right now, the annotation color can be used to format extracted annotations. Here is the description from the readme:

> Option to use annotation color for formatting of extracted annotations (thanks to [RAG2ko](https://github.com/RAG2ko))
> The annotation color can now be used to format extracted annotations. Just add some css styling to the hidden options for formatting. For example, change `formatAnnotationHighlight` to `<p style="background-color:%(color);">"%(content)" (%(cite))</p>`. The wildcard `%(color)` is replaced by the annotation color. This styling has the same effect but looks a little better: `<p><span style="background-color:%(color);">"%(content)"</span> (%(cite))</p>`

You can play around with this and test whether it works for different pdfs. The current implementation just takes the annotation color from the pdf (no color categorization). Let me know how you would like to use the categorization (e.g. a different note for each color category?) and I will try to guide you for the implementation.

**Comment by RAG2ko** [comment]
Hey! I tried the color extraction and it works great! The option to customize the output via css is a really good idea! I added the option to colorize notes as well (see jlegewie/zotfile/pull/153). I think this is useful.

Regarding the color categorization, I had the following features in mind:
- hidden preference to activate
- separate note for each color category (e.g. Extracted Annotations - Red,  Extracted Annotations - Green, ...)

Awaiting your guidance :)

**Comment by RAG2ko** [comment]
Let's move the discussion back to zotfile jlegewie/zotfile/issues/146

**Pull request closed without merging**
